name: Android SonarCloud CI

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - release/*
      - hotfix/*

jobs:
  build:
    name: Build & Analyze Android Project with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # ✅ Set up JDK 17 (required by Android Gradle plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      # ✅ Cache SonarCloud packages
      - name: Cache SonarCloud scanner packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # ✅ Grant execute permission to Gradle wrapper
      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew
      
      # ✅ Build project
      - name: Build project
        run: ./gradlew build

      # ✅ Run build & SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: sqp_7d5ea102d65f7a9f82a0578b4c32930d174afdce
        run: |
          ./gradlew clean build sonarqube \
            -Dsonar.projectKey=android-kotlin \
            -Dsonar.host.url=http://202.79.29.108:9000 \
            -Dsonar.login=sqp_7d5ea102d65f7a9f82a0578b4c32930d174afdce
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk